name: nasa_today
description: "NASA’s Astronomy Picture of the Day"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # navigation
  auto_route: ^8.1.2
  # state managment
  flutter_bloc: ^8.1.5
  # DI
  get_it: 7.6.7
  injectable: 2.3.2
  # serialization
  json_annotation: ^4.8.1
  # logging
  loggy: ^2.0.3
  pretty_dio_logger: ^1.3.1
  # network
  dio: ^5.4.0
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  http_interceptor: ^1.0.2
  equatable: ^2.0.5
  #support
  cupertino_icons: ^1.0.2
  #tests
  mockito: 5.4.4
  #animations
  animator:

dev_dependencies:
  flutter_test:
    sdk: flutter

  injectable_generator: 2.4.1
  flutter_lints: ^3.0.1
  build_runner: ^2.2.0
  json_serializable: ^6.6.2
  auto_route_generator: 8.0.0

flutter:
  uses-material-design: true